"""Subset the self-hosted Tabler icon font to the icons the site uses (content review, finding N20).

The full Tabler Icons webfont holds ~5,000 icons (760 KB WOFF2 + 198 KB CSS); the site uses about a hundred.

Run it from the abscerts/ folder whenever an icon is added or changed (a `ti ti-<name>` class, or a
frontmatter / data `icon: "ti-<name>"`):

    python scripts/subset-icons.py          # needs: pip install fonttools brotli

It downloads the full Tabler Icons webfont (pinned version, CSS + WOFF2) from jsDelivr, collects every
`ti-<name>` used in src/ and public/scripts/, and writes the trimmed CSS and WOFF2 into
public/vendor/tabler-icons-<version>/. `npm run build` then runs scripts/check-icons.mjs, which fails the build
if any page uses an icon the subset doesn't include.
"""
import hashlib
import io
import pathlib
import re
import sys
import urllib.request

from fontTools import subset
from fontTools.ttLib import TTFont

VERSION = "2.47.0"
BASE = f"https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@{VERSION}/"
ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "public" / "vendor" / f"tabler-icons-{VERSION}"
SOURCES = [ROOT / "src", ROOT / "public" / "scripts"]
EXTENSIONS = {".astro", ".md", ".mdx", ".ts", ".js", ".mjs"}


def get(url):
    with urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": "abscerts-subset-icons"}), timeout=60) as r:
        return r.read()


css = get(BASE + "tabler-icons.min.css").decode("utf-8")
codepoints = dict(re.findall(r'\.(ti-[a-z0-9-]+):before\{content:"\\([0-9a-f]+)"\}', css))
base_rule = re.search(r"\.ti\{[^}]*\}", css).group(0)
banner = re.search(r"/\*!.*?\*/", css, re.S).group(0)

used = set()
for folder in SOURCES:
    for f in folder.rglob("*"):
        if f.is_file() and f.suffix in EXTENSIONS:
            used |= set(re.findall(r"(?<![\w-])(ti-[a-z0-9]+(?:-[a-z0-9]+)*)", f.read_text(encoding="utf-8", errors="ignore")))
icons = sorted(n for n in used if n in codepoints)
unknown = sorted(n for n in used if n not in codepoints)
if not icons:
    sys.exit("No Tabler icons found in src/ or public/scripts/ — nothing written.")

font = TTFont(io.BytesIO(get(BASE + "fonts/tabler-icons.woff2")))
options = subset.Options()
options.flavor = "woff2"
options.layout_features = []
options.notdef_outline = True
# The site shows icons by codepoint (.ti-name:before), never by ligature, and fontTools can't parse Tabler's
# ligature table, so the layout tables are dropped.
options.drop_tables += ["GSUB", "GPOS", "GDEF"]
subsetter = subset.Subsetter(options)
subsetter.populate(unicodes=[int(codepoints[n], 16) for n in icons])
subsetter.subset(font)
buf = io.BytesIO()
font.flavor = "woff2"
font.save(buf)
woff2 = buf.getvalue()
version = f"{VERSION}-{hashlib.sha1(woff2).hexdigest()[:8]}"

(OUT / "fonts").mkdir(parents=True, exist_ok=True)
(OUT / "fonts" / "tabler-icons.woff2").write_bytes(woff2)
rules = "".join(f'.{n}:before{{content:"\\{codepoints[n]}"}}' for n in icons)
(OUT / "tabler-icons.min.css").write_text(
    f"/* Tabler Icons webfont {VERSION} (MIT, see LICENSE), subset to the {len(icons)} icons this site uses\n"
    f"   (content review, N20). Generated by scripts/subset-icons.py; re-run it after adding an icon. */\n"
    + (f"/* unknown: {' '.join(unknown)} */\n" if unknown else "")
    + f"{banner}"
    f'@font-face{{font-family:"tabler-icons";font-style:normal;font-weight:400;font-display:block;'
    f'src:url("./fonts/tabler-icons.woff2?v={version}") format("woff2")}}'
    f"{base_rule}{rules}\n",
    encoding="utf-8",
)
print(f"{len(icons)} icons -> fonts/tabler-icons.woff2 ({len(woff2) // 1024} KB), tabler-icons.min.css")
if unknown:
    print("Not Tabler icon names (ignored; check for typos):", ", ".join(unknown))
